### ISSUE TITLE
manipulate helices (e.g., delete) more like other items

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#129]
Currently helices are deleted by a different mechanism than other items. Other items can be selected, and deleted by pressing the delete key.

To delete a helix, the pencil mode must be on, and the helix clicked. This is unexpected behavior to someone who's been using the delete functionality in the main view.

Similarly, strands are added in "pencil" mode, but not helices. Removing the "helix" mode entirely and just treating the side view similar to strands in the main view while in "pencil" mode. (Although deletion is possible in Select mode as well by pressing delete when some are selected.)

If this is done correctly, we should be able to get rid of helix edit mode entirely.

**Comment by dave-doty** [comment]
The pencil mode suggestion is implemented now, but I still want to be able to delete helices by selecting them and pressing the delete key, and to move them by selecting and click+drag.

**Comment by UnHumbleBen** [comment]
@dave-doty  What should the expected behavior be if the user selects elements in the main view as well as helices in the side view (some of the selected main view elements may or may not be on a selected helix)? I think it would be easier to implement if we make add the requirement that in order to delete helices, there must be no elements selected in the main view. In addition to being simpler to implement, it makes more sense for some use cases:

For example, this would be helpful if the user selects some helices and uses the "display only selected helix feature". If they are editing, they may select elements in the main view and delete things. They would not expect the helices that they have selected for viewing purposes to be deleted. For this reason, I think it makes sense to require that there are no main view elements selected to delete helices via the DELETE key. What do you think?

**Comment by dave-doty** [comment]
>  I think it would be easier to implement if we make add the requirement that in order to delete helices, there must be no elements selected in the main view. In addition to being simpler to implement, it makes more sense for some use cases:

I agree. Right now the select modes made the following three mutually exclusive:

- strands
- crossovers/loopouts
- 5'/3' ends

I suggest adding a fourth group, mutually exclusive with the other three:

- helices

As with the others, picking the "helix" select mode should immediately unselect any non-helices that are currently selected (and vice versa).

**Comment by UnHumbleBen** [comment]
So if my understanding is correct, the user would not be allowed to select any main view elements while "only display selected helix" is checked?

**Comment by dave-doty** [comment]
No, the "only display selected helix" should be independent of the "select mode". If "select mode" is helix, then helices can be selected. "only display selected helix" is a independent option and would no effect when no helices are selected (such as when "select mode" is not helix).

**Comment by UnHumbleBen** [comment]
Perhaps I should have been clearer. Instead of saying user "would not be allowed to select any main view elements", I should have said the user would be discouraged from selecting main view elements while "only display selected helix" is checked.

For example, consider that a user sets the select mode to helix and selects a few helices, and turns on "only display selected helix", so that only the selected helices will be displayed in the main view. When the user attempts to switch select mode to select "strands", all the helices in the main view will disappear because switching select modes will deselect all the currently selected helices, and because "only display selected helix" is still checked, the main view will display nothing.

Is this the intended behavior? It would be impossible for the user to edit while "only display selected helix" is checked because they would not be able to select anything to copy and paste strands or move DNA ends.

**Comment by dave-doty** [comment]
One way to solve this is that "only display selected helices" should display all helices when no helices are selected. It is only when a strict subset are selected that the view should actually change.

It just seems easier to let "only display selected helices" be independent of whatever else is configured in the UI (such as the select mode).

Otherwise it would introduce some confusing state-dependent information for us, and the use, to remember.

**Comment by UnHumbleBen** [comment]
Wouldn't displaying all helices when none of the helices also lead to confusing behavior?

Going back to my example above, now when the user tries to select "strands" select mode, every single helix is now displayed, instead of just the ones that the user previously selected. Perhaps it's okay to display none of the helices while no helix is selected and "only display selected helices" is on? It would force the user to manually turn that check mark off, but I think this is preferable to displaying all of the helices, which would contradict what the "only display selected helix" check mark is supposed to do.

In any case, I agree that the helix selection should be separated from main view element selections, so I will add helix as a mutually exclusive select mode.

**Comment by dave-doty** [comment]
> Wouldn't displaying all helices when none of the helices also lead to confusing behavior?

Perhaps. The main reason it works the way it does now (where selecting none displays all of them) is that there's no point in hiding every helix, since there's nothing left to view. But I agree that if no helices were selected, a user might get confused and think the view option doesn't work since it doesn't change the view when they turn the option on. So I'm happy to have it hide the whole view if no helices are selected.

The main danger here is that if we are not persisting the set of selected helices in localStorage, then refreshing the page while some helices are selected would make it look like the design has disappeared, and the user might panic and think they lost their work. (And then they might actually lose their work in the process of trying to fix it.)

But if at least one helix is always displayed, then that gives the user a way to realize what is happening.

One option is to simply display a message where the design would be, indicating that the design is present but no helices are selected, and that to see some of the design, they should either select some helices, or uncheck the view option.

However, one thing I didn't think about is this: the main reason to display a subset of helices is to make it easier to inspect *and edit* a design. Some of that editing would involve selecting other objects, for example to move, copy them, or delete them. So actually now I changed my mind, and I think it makes sense to keep the current selection behavior, where helices can always be selected, regardless of the select mode. (And so there's no need for a special helix select mode.)

Perhaps it's easiest to implement helix deletion by a special rule: if any other objects are selected, then they are deleted, and if no objects but helices are selected, then the helices are deleted.

Another option is that helices are deleted via a context menu, so the delete key only applies to non-helix objects.

Both options would make helix deletion work differently than other objects, but they are still better than the current situation where deleting many helices requires clicking on each one.

It would also be good to implement moving and copy/pasting of helices, eventually. (This is a larger undertaking; this took quite a bit of work to implement for strands and ends.) The same issues will arise there, where we might have to say that if helices and strands are both selected, then Ctrl+C means copy the strands, but if only helices are selected, then Ctrl+C means copy the helices.

**Comment by UnHumbleBen** [comment]
> Perhaps it's easiest to implement helix deletion by a special rule: if any other objects are selected, then they are deleted, and if no objects but helices are selected, then the helices are deleted.

Okay, I will implement this option.
