### ISSUE TITLE
Adjusting grid_position v-coordinate does not update main view

### ISSUE THREAD

**Issue by UnHumbleBen** [UC-Davis-molecular-computing/scadnano#166]
The cause of the bug seems to lie in the @memoize attribute for the svg_position. Once svg_position is computed once, the field (I believe the builder caches the value in svg_builder__) is never updated again, and constantly refers to the old cached value. Not sure how to approach fixing this.

**Comment by dave-doty** [comment]
It's true that memoized properties are not ever computed again, but neither are any other properties, because built objects are immutable. The difference is that the memoized properties are deterministic functions of the other properties, so can be computed based on the others, and are lazily computed as needed.

If a memoized property such as `svg_position` is not being updated when needed, it's because the whole Helix object it is a part of should be updated. If that `Helix` object is updated, then the `svg_position` will be recomputed (or more precisely, computed for the first time on the newly created `Helix` object).

**Comment by dave-doty** [comment]
To reproduce, draw some helices and then update the *v*-coordinate of the grid position of one helix. Nothing will move in the main view (but it will in the side view), but the helix's vertical position should be adjusted in the main view.
