### ISSUE TITLE
set up automated deployment from `dev` into a dev site

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#337]
For example, the dev site could be https://scadnano.org/dev, or https://dev.scadnano.org.

This will help us to keep the stable version more stable with less frequent updates (still involving merging `dev` into `master`), while still allowing people to test new features who do not want to install Dart and run a local scadnano server.

We should also do automated releases on the `dev` branch, so that people using the `dev` branch can see what features have been introduced.

This should be accompanied by a workflow where we make new branches for implementing most new features/bugfixes, which are then merged into `dev` with a pull request.

**Comment by dave-doty** [comment]
This looks as though it might be impossible to do with GitHub pages as the host:

https://github.community/t/can-i-publish-multiple-branches-of-a-repository-on-github-pages/10314

**Comment by UnHumbleBen** [comment]
An idea I can think of is configuring the github-pages workflow to checkout `master` branch, and build into a `build` folder, and then checkout the `dev` branch and build into the `build/dev` folder. Then serve `build` on gh-pages.

**Comment by dave-doty** [comment]
The idea should be that only the dev branch is deployed to the dev server when changes are committed to `dev`, leaving `master` alone. So these should be two separate GitHub actions, one triggered by committing to `master`, and the other triggered by committing to `dev`.

**Comment by UnHumbleBen** [comment]
I think we can do this with just one workflow because if a change is commited to `dev`, then the action would rebuild both `master` and `dev` anyways. The `master` build wouldn't change, but the `dev` build would, so effectively, only the `dev` build is changed. So the idea for one workflow is we always build both `master` and `dev` whenever either branches are pushed.

Nevertheless, the idea of having two workflows is also nice to avoid excessive rebuilding, so that would be accomplished as follows:
1. A new workflow should be added, titled something like `gh-pages-dev` which checks out `dev` branch and `gh-pages` branch , builds into `gh-pages-repo/dev`, and deploys it.

2. The current `gh-pages` workflow should be modifed so that it checks out `gh-pages` branch and `master` branch, builds into `gh-pages-repo`, and deploys it. *Currently, the workflow does **not** pull from gh-pages branch and just overwrites whatever is currently deployed. This will no longer work because we need to preserve the `dev` subdirectory*.

**Comment by dave-doty** [comment]
I think I see. So the idea is that deployment is always done from gh-pages to the GitHib pages site. But when the workflow is the `dev` branch workflow, only the `dev/` subdirectory is being modified. So after it is deployed to the GitHub pages site, it won't change what is shown at https://scadnano.org, only what is at https://scadnano.org/dev

> builds into gh-pages-repo/dev, and deploys it.

Did you mean to say "builds into gh-pages/dev, and deploys it."? What's gh-pages-repo?

**Comment by UnHumbleBen** [comment]
I used `gh-pages-repo` to designate the name of the temporary repository for which the `gh-pages` branch is cloned in. I wanted to distinguish the branch name from the repository name since there isn't a repository named gh-pages, but yes, the idea you have is essentially what I had in mind. Inside the repository for the gh-pages branch, there would be a `dev` subdirectory where all the builds for `dev` would go to.

**Comment by UnHumbleBen** [comment]
I can try manually building `dev` into the `gh-pages` branch and see if this idea can work.

**Comment by UnHumbleBen** [comment]
Alright here it is: https://scadnano.org/dev/

**Comment by dave-doty** [comment]
Great, I'll try it out on my next commit. Thanks!

**Comment by dave-doty** [comment]
I merged changes from another branch into dev a few minutes ago, but it appears that the gh-pages deployment didn't happen (you can see the last deployment was yesterday):

https://github.com/UC-Davis-molecular-computing/scadnano/actions?query=workflow%3A%22github+pages%22

![image](https://user-images.githubusercontent.com/19274365/86501853-db737900-bd51-11ea-9630-93b2df429df1.png)

Somehow, the dev website is up: https://scadnano.org/dev/

But it does not have changes that I just implemented in the latest merge into dev. For example, in the dev branch, you can now right-click on helices in the side view to bring up their context menu (same as in the main view). But on https://scadnano.org/dev/, right-clicking on helices in the side view still just brings up the default browser context menu.

**Comment by UnHumbleBen** [comment]
There shouldn't be a deployment. I haven't set up the workflow yet :)

I'm surprised dev is still up. Perhaps the `master` gh-pages workflow doesn't need to change then, and I can just focus on setting up the `gh-pages-dev` workflow

**Comment by UnHumbleBen** [comment]
Because of issues with `cd` in bash script, I had to tweak the method slightly, but the result is the same. The `dev` branch will deploy in a `dev` subdirectory.

The change is that rather than having two directories `dev-repo` and `gh-pages-repo`, the directories are nested:
`dev-repo` and `dev-repo/gh-pages-repo`. Then, the action builds into `dev-repo/gh-pages-repo/dev` before serving `gh-pages-repo/`

The same idea applies to deploying master, using `master-repo` instead of `dev-repo`.

**Comment by dave-doty** [comment]
Thanks!

I'm a bit confused by some of the terms.

> Because of issues with cd in bash script

Which bash script is this? I see that https://github.com/UC-Davis-molecular-computing/scadnano/blob/dev/.github/workflows/gh-pages-dev.yml has bash commands in it. I suppose that turns into some bash script when the action executes? (Even though the bash script itself is not a file in one of our repos)

> the directories are nested: `dev-repo` and `dev-repo/gh-pages-repo`

Where are these directories exactly? I see `gh-pages-repo` referenced here: 

https://github.com/UC-Davis-molecular-computing/scadnano/blob/dev/.github/workflows/gh-pages-dev.yml#L19

Although I'm not exactly sure where it is a directory. Is this a directory that temporarily exists while the GitHub Action is executing?

**Comment by UnHumbleBen** [comment]
> Which bash script is this? I see that https://github.com/UC-Davis-molecular-computing/scadnano/blob/dev/.github/workflows/gh-pages-dev.yml has bash commands in it. I suppose that turns into some bash script when the action executes? (Even though the bash script itself is not a file in one of our repos)

Ah yes, my bad, I used the term "bash script" when because the issue I was having was similar to that if you try to run `cd` in a bash script. I don't know if a github action is a bash script exactly.

> Although I'm not exactly sure where it is a directory. Is this a directory that temporarily exists while the GitHub Action is executing?

Yes, those directories are temporary directories created by the Github action.

**Comment by dave-doty** [comment]
Closed in PR #342
