### ISSUE TITLE
allow user to disable hiding of non-selected helices

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#51]
Currently, when some but not all helices are selected in the side view, only the selected helices are displayed. Add an option for them all to remain displayed no matter the selection.

**Comment by UnHumbleBen** [comment]
@dave-doty I think an view checkbox named "hide non-selected helices" would make more sense than a "disable hide non-selected helices" checkbox. So when the checkbox is checked, the main will only display selected helices, and when the checkbox is not checked, the main will display all helices. What do you think?

**Comment by dave-doty** [comment]
Yes, that makes sense.

**Comment by UnHumbleBen** [comment]
@dave-doty Do you think the stored helices should be stored in local storage? I'm not sure which behavior would make more sense. Should users expect the helices they selected to stay selected when they refresh the page? Or like other selections, the selections should be removed. If helix selections are to be removed upon refresh, then it might be helpful to let the `Only Display Selected Helices` default to false because otherwise, the user would always see nothing in the main view if they previously had `Only Display Selected Helices` checked on. What are your thoughts?

**Comment by dave-doty** [comment]
No, I don't want it in local storage. It's easy enough to re-select helices after a reload, especially since they can drag a selection box.
