### ISSUE TITLE
copy strands from a design, load a new design, and then paste the strands into the newly loaded design

### ISSUE THREAD

**Issue by damienwoods** [UC-Davis-molecular-computing/scadnano#520]
Provide a simple pathway to merging two designs. The use-case is that the user has two scadnano designs and wishes to combine parts of both to make a third. I'm not sure how best to do this, but one method would be to allow the user to open a second design into an already-open first design. The second design might be displayed off to the right-hand side. The user can then use copy-paste to move strands between the designs.

**Comment by dave-doty** [comment]
Probably the simplest way to implement this is to allow copy/paste of strands across designs. I see two options:

1. Use the system copy-buffer to copy and paste between two different windows that both have scadnano open. In general it is not recommended to use scadnano in two windows with the same browser, since they will both be writing to the same localStorage, but with one Chrome and one Firefox browser, this could work.

2. Put the copy buffer into localStorage. Then one can copy several strands from a design, load a new design in the same browser window, then paste those strands. 

Option 2 seems simpler.
