### ISSUE TITLE
copy strand details to clipboard as human-readable text

### ISSUE THREAD

**Issue by damienwoods** [UC-Davis-molecular-computing/scadnano#536]
Feature request: Give a way to copy all strand info to the system clipboard in human-readable text format. This form of copying would not be needed so often (e.g. when discussing a design with a colleague over email it saves me typing out the name, or when sanity checking sequence against some other seq on my computer it saves me manually typing out the sequence), so I would personally prefer it to appear only in the 'right click' and 'Edit' menus as a second form of copy, additional to the standard notion.

**Comment by dave-doty** [comment]
I'm not sure whether the browser security restrictions would let it access the system clipboard. But another file export option could be used to write information to a text file.

What details should be included, and in what format?

**Comment by damienwoods** [comment]
The goal is to copy strands from one instance of scadnano to another. So whatever details/format makes that work.

**Comment by dave-doty** [comment]
> The goal is to copy strands from one instance of scadnano to another. So whatever details/format makes that work.

That's a different issue, and it's been implemented: #520.

This issue is about implementing "*copy all strand info to the system clipboard in human-readable text format*". But there's quite a few details about the Strand stored internally, so I'm looking for guidance about what Strand details would be useful.

**Comment by dave-doty** [comment]
One idea would simply be to write the JSON the way it is exported to the `.sc` file, which was designed to be human readable, e.g.:

![image](https://user-images.githubusercontent.com/19274365/103227820-2f67b080-48e4-11eb-8cf9-66bf14701e6e.png)

can be exported as

```json
{
  "name": "strand with biotin",
  "color": "#57bb00",
  "sequence": "ACGTTACGTTACGTTACGCGTTACGTTACGTTAC",
  "domains": [
    {"name": "domain 1", "helix": 0, "forward": false, "start": 24, "end": 40, "insertions": [[26, 2]]},
    {"name": "domain 2", "helix": 1, "forward": true, "start": 24, "end": 40}
  ],
  "5prime_modification": "/5Biosg/"
}
```

The advantage over looking through the `.sc` file is that you don't have to go hunting for one or a few strands in a large design. You could just select them and press "Copy selected strand info to clipboad" to make only their JSON data show up. 

Despite the large number of data fields stored by Strands internally, the JSON export code doesn't bother writing anything if it's equal to its default value (e.g., there's no information about 3' or internal modifications above, since it doesn't have any).

**Comment by damienwoods** [comment]
Sounds good.
