### ISSUE TITLE
fix bug where color picker switches to RGB while typing in a hex code

### ISSUE THREAD

**Issue by aersh** [UC-Davis-molecular-computing/scadnano#547]
Color picker switches to RGB while typing in a hex code, making it challenging to specify strand colors as hex codes. The issue has appeared on a Mac with both Firefox and Chrome.

![20201213_scadnano_hex_rgb](https://user-images.githubusercontent.com/49655918/102034427-fa0f7e80-3d8b-11eb-94bf-0194d12e6980.gif)

**Comment by UnHumbleBen** [comment]
This bug is caused by the [React Color library](https://github.com/casesandberg/react-color/issues/432). There [is a fix in version 2.14](https://github.com/casesandberg/react-color/pull/461#issuecomment-369095315). Unfortunately, [the owner does not want to make a minified file (UMD) for version 2](https://github.com/casesandberg/react-color/issues/310#issuecomment-270661558). and only made UMD for [version 3](https://unpkg.com/react-color@3.0.0-beta.3/dist/react-color.min.js) which is what we have been using.

## Possible Fixes:
1. Make UMD ourself by cloning [React Color](https://github.com/casesandberg/react-color/issues/310) and bundling. I tried doing this but ran into issues with babel.
2. Stick with the minified file we have put choose a [different color picker](http://casesandberg.github.io/react-color/). Currently, the bug is only on the Chrome color picker, so we can choose another picker. Personally, I think the Sketch color picker looks the best, and seems most similar to the current Chrome color picker.

**Comment by dave-doty** [comment]
Would fixing this issue help?

https://github.com/UC-Davis-molecular-computing/scadnano/issues/346

I have barely any understanding of how one properly uses JS libraries. All the ones we use now are just minified files we include, but the issue above is about using the more advance recent technology, which might be compatible with the new version of the React Color picker.

**Comment by dave-doty** [comment]
> ## Possible Fixes:
> 1. Make UMD ourselves by cloning [React Color](https://github.com/casesandberg/react-color/issues/310) and bundling. I tried doing this but ran into issues with babel.
> 2. Stick with the minified file we have put choose a [different color picker](http://casesandberg.github.io/react-color/). Currently, the bug is only on the Chrome color picker, so we can choose another picker. Personally, I think the Sketch color picker looks the best, and seems most similar to the current Chrome color picker.

Since npm packages aren't well-supported in Dart (see #346), looks like option #2 is the most straightforward.
