### ISSUE TITLE
older versions of scadnano not available

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#571]
I tried navigating to older versions of scadnano, but they are not being served, e.g.
https://scadnano.org/v0.14.1 shows

![image](https://user-images.githubusercontent.com/19274365/107449304-2fb8b580-6af8-11eb-84d3-0b8f7f9ef10e.png)

**Comment by UnHumbleBen** [comment]
Working on this now. I made a [hotfix on the Github Pages branch](https://github.com/UC-Davis-molecular-computing/scadnano/commit/b6bed08a5c3640442d97db981d516e30c01dbae6). It takes about 10 minutes for the CDN to repopulate with the updated files, so hopefully by then, the link will be working again.

In the mean time, trying to find the root cause

**Comment by UnHumbleBen** [comment]
# TODO:

* Fix Github Action so that directory are named with `v`
* Add `/index.html` to anchor tag links because omitting `/index.html` seems to give inconsistent results for whether the page is found or not
* Remove v0.14.1 from list of available versions in constants.dart because this version doesn't exist in [the Release page](https://github.com/UC-Davis-molecular-computing/scadnano/releases)

**Comment by UnHumbleBen** [comment]
@dave-doty 

The older versions should now be available now. https://scadnano.org/v0.14.0 should work. If not, try https://scadnano.org/v0.14.0/index.html
