### ISSUE TITLE
add dart format configuration options to text file stored in repo

### ISSUE THREAD

**Issue by dave-doty** [UC-Davis-molecular-computing/scadnano#777]
This will ensure that if we run dart format, we all run it the same way.

**Comment by dave-doty** [comment]
> (the `.idea` directory will also have to be changed in `.gitignore`)

I don't want to include all of `.idea` in the repo because it includes somethings that are system-specific, e.g., absolute links to certain file names. I often use three computers (desktops at home and work, and laptop) and see when `.idea` is updated by one of them, it breaks the others.

Other options are

1. figure out how to ignore all of `.idea` in `.gitignore` except for one file; I don't know if this is possible.
2. figure out how to store `.idea` for the project outside of the directory with the git repo; this might involve me simply putting the git repo directory one level down and then telling Webstorm (or VSC for others) that the project root directory is one up from the repo, so that it doesn't try to store settings inside the repo itself.

**Comment by EdwinChang24** [comment]
We could use [the JetBrains template from gitignore.io](https://github.com/toptal/gitignore/blob/master/templates/JetBrains.gitignore). This should only ignore the files under `.idea/` that are user-specific and should not be in Git.

By the way, we should update the `.gitignore` to include more templates because it seems like only a Dart template is included currently. We can put as many templates as we want in the `.gitignore` and they shouldn't conflict with each other since it's just a list of globs. There are some good templates [here](https://github.com/toptal/gitignore) and [here](https://github.com/github/gitignore) that we could use.

**Comment by dave-doty** [comment]
> By the way, we should update the .gitignore to include more templates because it seems like only a Dart template is included currently.

What do you mean by templates?

**Comment by EdwinChang24** [comment]
Every `*.gitignore` file in those repos is considered a gitignore 'template' for some language/framework, and the developer is meant to copy all of the templates related to their project into their `.gitignore` file, and then they never have to touch the `.gitignore` file ever again. Or, there is a generator [here](https://www.toptal.com/developers/gitignore/) where you can easily choose some templates and generate a project `.gitignore` file.

Using templates can allow us to be mostly sure that the files that need to be ignored get ignored, without spending too much time constantly messing with the `.gitignore` file. And if we need to ignore any other files that aren't in a template, we can always add them to `.gitignore` manually.

**Comment by dave-doty** [comment]
Oh, I see. Sure, let's add the JetBrains gitignore template. Might be good to use a VSC one as well, though I'm not sure if VSC creates a config folder in the project directory or not.
