### ISSUE TITLE
Feature request: selection preserves color

### ISSUE THREAD

**Issue by Sam-Davidson** [UC-Davis-molecular-computing/scadnano#870]
Currently, selecting a strand turns it pink, so the color of that strand can't be known without deselecting it or trying to change it. It would be better for selection to be displayed as a highlight or a thick black outline.

**Comment by dave-doty** [comment]
Let's solve this with a new option in the View menu that allows the color to be retained upon selection.

The relevant CSS starts at line 667 in web/scadnano-styles.css. We can make an alternate selector that leaves out the `stroke: hotpink;` part of the formatting.

**Comment by dave-doty** [comment]
FYI, this had a fairly major bug I just discovered and fixed in another branch. Here's the commit that fixed it:

https://github.com/UC-Davis-molecular-computing/scadnano/pull/960/commits/35f4e9f44ab63b244c6ffa690155dd85e4691708

The problem was that the prop `retain_strand_color_on_selection` was added to various view components like `DesignMainLoopout` and `DesignMainDomain`, but it was not being passed to them from the parent component `DesignMainStrandPaths` and caused a crash when testing `if (props.retain_strand_color_on_selection)`, since that field was null rather than being true or false.

This really seems like the kind of thing static typing in OverReact is supposed to help prevent. There's apparently some way to get OverReact to warn us when a prop for a component is not being set, but I don't know how to do it. This is a very common bug.

Another thing that might prevent this bug is if we get rid of the prop-drilling and use "React context" instead to pass props down a view tree hierarchy. I was always afraid that would have performance problems, so have been afraid to try it. Plus it would require a big re-write of most of the view code. But the view code would hopefully be much simpler after that, since prop-drilling adds tons of boilerplate.
